# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20170727_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
