# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_postmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
